services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: buy-01-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2182:2181"
    networks:
      - buy-01-network

  mongodb:
    image: mongo:6.0
    container_name: buy-01-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./uploads:/data/db
    networks:
      - buy-01-network

  kafka:
    image: confluentinc/cp-kafka
    container_name: buy-01-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - buy-01-network

  service-registry:
    image: buy01-pipeline-service-registry:latest
    container_name: buy-01-service-registry
    ports:
      - "8761:8761"
    networks:
      - buy-01-network

  api-gateway:
    image: buy01-pipeline-api-gateway:latest
    container_name: buy-01-api-gateway
    ports:
      - "8080:9999"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-registry:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: api-gateway
    depends_on:
      - kafka
      - service-registry
    networks:
      - buy-01-network

  user-service:
    image: buy01-pipeline-user-service:latest
    container_name: buy-01-user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongodb:27017/userdb?authSource=admin
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-registry:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: user-service
    depends_on:
      - kafka
      - service-registry
      - mongodb
    networks:
      - buy-01-network

  product-service:
    image: buy01-pipeline-product-service:latest
    container_name: buy-01-product-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongodb:27017/productdb?authSource=admin
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-registry:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: product-service
      MEDIA_PUBLIC_URL: http://13.61.234.232:8080/api/media
    depends_on:
      - kafka
      - service-registry
      - mongodb
    networks:
      - buy-01-network

  media-service:
    image: buy01-pipeline-media-service:latest
    container_name: buy-01-media-service
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongodb:27017/mediadb?authSource=admin
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-registry:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: media-service
      API_GATEWAY_URL: http://13.61.234.232:8080/api/media
    volumes:
      - ./media-service/uploads:/app/uploads
    depends_on:
      - kafka
      - service-registry
      - mongodb
    networks:
      - buy-01-network

  frontend:
    image: buy01-pipeline-frontend:latest
    container_name: buy-01-frontend
    ports:
      - "4200:80" # HTTP
    depends_on:
      - api-gateway
    networks:
      - buy-01-network

networks:
  buy-01-network:
    driver: bridge
