server:
  port: 8443 # HTTPS port
  ssl:
    enabled: true
    key-store: file:/app/certs/localhost.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: localhost

spring:
  application:
    name: api-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration # Disable security
  cloud:
    compatibility-verifier:
      enabled: false # From your application.properties
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # --- User Service Routes ---
        - id: user-service-api
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**, /api/users/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # --- Product Service Routes ---
        - id: product-service-api
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # --- Media Service Routes ---
        - id: media-service-api
          uri: lb://MEDIA-SERVICE
          predicates:
            - Path=/api/media/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:4200"
              - "https://localhost:4201"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
